### ISSUE TITLE
Unrecognized argument: '--nodeprof'

### ISSUE THREAD

**Issue by HL87-sys** [Haiyang-Sun/nodeprof.js#64]
I got `ERROR: Unrecognized argument: '--nodeprof'` when setting up [basic installation](https://github.com/Haiyang-Sun/nodeprof.js/blob/master/Tutorial.md#run-using-graalvm) on both Linux and MacOS. It seems the node binary in the pre-built GraalVM does not support the `--nodeprof` option... Building everything from source works for me.

BTW, the link for downloading "a snapshot of the latest nodeprof" is not working. So I checked out and compiled nodeprof.jar.

Thanks!

**Comment by Haiyang-Sun** [comment]
Hi @HL87-sys ,

Thanks a lot for trying NodeProf and giving us feedback.
The cause is that the nodeprof.jar you built is based on a later version of Graal.js with the latest fixes and new features that makes it incompatible with the GraalVM release you downloaded.

The solution is to provide a nodeprof.jar snapshot for each corresponding GraalVM release.
We plan to do so for the next GraalVM release with all the recent fixes and features included.

Or you can build a GraalVM binary yourself by running ```mx --dy nodeprof,/substratevm --force-bash-launchers=true --disable-polyglot build``` in ```$ROOT/graal/vm```

This should produce a graalvm binary in ```$ROOT/graal/vm/latest_graalvm/``` with nodeprof integrated.

Then you should be able to run nodeprof with the following commands:
```$YOURGVM/bin/node --jvm --nodeprof --experimental-options```
(Still, you need to add the jalangi part option to run Jalangi analysis.)

**Comment by HL87-sys** [comment]
I see, thanks. When is the next release?

**Comment by alexjordan** [comment]
Hi @HL87-sys!

The GraalVM release is expected for November. We are going to build a release version of NodeProf then. In the meantime I've fixed the broken links you pointed (thanks!).

**Comment by Haiyang-Sun** [comment]
Hi @HL87-sys 
Please find one pre-release of NodeProf here:
https://github.com/Haiyang-Sun/nodeprof.js/releases/tag/09.12.2019

You should run NodeProf directly in the release using command like below:
```
./bin/node --experimental-options --nodeprof ./nodeprof/nodeprof.js --analysis  ./nodeprof/examples/example.js ./nodeprof/tests/helloworld.js 
```
